<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>com.github.PEAKModding.PEAKLib.UI</AssemblyName>
    <AssemblyTitle>PEAKLib.UI</AssemblyTitle>
    <Version>1.7.1</Version>
  </PropertyGroup>

  <!-- NuGet metadata -->
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>PEAKModding.PEAKLib.UI</PackageId>
    <Description>UI module of the PEAKLib community API for the game PEAK.</Description>
    <Authors>$(Authors), Rafa, darmuh</Authors>
  </PropertyGroup>
  <ItemGroup>
    <None Include="./Assets/README.md" Pack="true" PackagePath="/" />
    <None Include="./Assets/icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PEAKLib.Core/PEAKLib.Core.csproj" />
  </ItemGroup>

</Project>
