<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>com.github.PEAKModding.PEAKLib.ModConfig</AssemblyName>
    <AssemblyTitle>PEAKLib.ModConfig</AssemblyTitle>
    <Version>1.8.1</Version>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PEAKLib.Core/PEAKLib.Core.csproj" />
    <ProjectReference Include="../PEAKLib.UI/PEAKLib.UI.csproj" />
  </ItemGroup>

</Project>
